.PHONY: build-StorageLayer

build-StorageLayer:
	mkdir -p "$(ARTIFACTS_DIR)/python"
	cp -r src/storage "$(ARTIFACTS_DIR)/python/storage"
	rm -rf "$(ARTIFACTS_DIR)/python/storage/__pycache__"
	rm -rf "$(ARTIFACTS_DIR)/python/storage/.pytest_cache"
