.PHONY: build-AgentLayer

build-AgentLayer:
	mkdir -p "$(ARTIFACTS_DIR)/python"
	cp -r src/agent "$(ARTIFACTS_DIR)/python/agent"
	rm -rf "$(ARTIFACTS_DIR)/python/agent/__pycache__"
	rm -rf "$(ARTIFACTS_DIR)/python/agent/.pytest_cache"
